# Generated by Django 5.1.4 on 2025-01-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_api', '0002_rename_comapany_company'),
        ('locations_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies_api.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='locations',
            name='city_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='locations',
            name='country',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='locations',
            name='country_abbrev',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='locations',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='locations',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
